---
abstract: 'Perl extension for maintaining test directories.'
author:
  - 'Steve Sanbeg <sanbeg@cpan.org>'
build_requires:
  Test::Builder::Tester: 0
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Directory
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: https://github.com/sanbeg/Test-Directory
version: 0.01
